### ISSUE TITLE
SealPIR does not currently handle d>2

### ISSUE THREAD

**Issue by sga001** [Microsoft/SealPIR#2] opened 2018-06-02 20:33 UTC
The current implementation does not work correctly when the database is represented a d-dimensional hyperrectangle when `d` is larger than 2. This is a known issue and we are currently working on it.

**Comment by sachaservan** [comment] 2019-02-04 02:35
Any updates on this? Is the cause of the issue known?

**Comment by tachyonstar** [comment] 2019-02-04 03:45
Unfortunately I haven't had much time to fix this. I think the main issue is that the logic of generate_reply in pir_server.cpp (https://github.com/Microsoft/SealPIR/blob/master/pir_server.cpp#L145) does not work when d > 2.

**Comment by sga001** [comment] 2019-02-04 03:49
I think the logic of ``generate_reply`` in ``pir_server.cpp`` (https://github.com/Microsoft/SealPIR/blob/master/pir_server.cpp#L145) is not right when d > 2. Unfortunately, I haven't had much time to fix it. I'll see if I can set aside a few hours in the next week or so and take a closer look.

**Comment by sachaservan** [comment] 2019-02-07 18:36
@sga001 thanks for replying. I am willing to investigate it, however, I accidentally update the SEAL library on my machine and cannot downgrade to 2.3.1 since it's no longer available online. Is there an archive of it?

**Comment by sga001** [comment] 2019-02-07 19:31
There is an updated version of SealPIR that works with the latest version of SEAL and will be released in a couple of days. I'd probably wait for that instead.

**Comment by kimlaine** [comment] 2019-02-09 04:50
@sachaservan An updated version of SealPIR that works with Microsoft SEAL 3.1.0 is now available.

**Comment by sachaservan** [comment] 2019-02-09 14:03
@sga001 @kimlaine Thank you!

**Comment by haochenuw** [comment] 2019-02-12 03:38
Even with my fix the issue with d > 2 still remains. I will investigate.

**Comment by haochenuw** [comment] 2019-02-18 00:48
This is fixed now.

**Closed as completed by haochenuw** 2019-02-18 00:48 UTC
